/**
 * @providesModule AppConstants
**/

export {
  WINDOW_WIDTH,
  WINDOW_HEIGHT,
  STATUSBAR_HEIGHT,
  NAVBAR_HEIGHT,
  HEXAGON_SIZE,
  HEXAGON_IMAGE_SIZE,
  HEXAGON_PADDING,
  HEATMAP_HEXAGON_X_COUNT,
  HEXAGON_AVATARS,
  HEXAGON_LOGO,
  LAYOUT_ANIMATION_CONFIG,
  CAPTURE_VIDEO,
  CAPTURE_PICTURE,
  CAMERA_ROLL_PHOTOS,
  CAMERA_ROLL_VIDEOS,
  SEARCH_DELAY_TIME,
  SEARCH_FILTERS,
  VALIDATIONS,
  SOCIAL_ITEMS,
  API,
  NO_PAN_HANDLERS_SCENES,
  NO_TRANSITION_SCENES,
  JUST_HIVE_HOST,
  REC_ANIMATION_TIMER,
  REC_ANIMATION_DELAY_TIME,
  REC_ANIMATION_LIMIT_TIME,
  REC_PATH_AMOUNT,
  REC_BUTTON_FRAME,
  THUMB_SIZE,
  CLICK_DURATION,
  REGEXPS,
  FEED_USER_INFO_OVERLAY_WIDTH,
  FEED_USER_INFO_OVERLAY_HEIGHT,
  FEED_ITEM,
  LOCAL_CODES,
  STORAGE_KEY_NOTIFICATIONS,
  NO_BACK_ANDROID
} from './constants';
export ExtendableError, {
  ConnectionError,
} from './errors';
